main/urls.py
from django.conf.urls import url

from . import views

app_name="main"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about/$', views.about, name="about"),
    url(r'^thanks/$', views.thanks, name="thanks"),
    url(r'^contact/$', views.ContactView.as_view(), name="contact"),
    url(r'^contacts/$', views.ContactsView.as_view(), name="contacts"),
    url(r'^customer/(?P<customer_id>[0-9]+)/$', views.viewCustomer, name='customer'),
    url(r'^customer/edit/(?P<customer_id>[0-9]+)/$', views.editCustomer, name='edit_customer'),
    url(r'^customer/delete/(?P<customer_id>[0-9]+)/$', views.deleteCustomer, name='delete_customer'),
    url(r'^customers/$', views.CustomersView.as_view(), name="customers"),
]

sup_world/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("main.urls", namespace="main", app_name="main")),
]

main/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Contacts(models.Model):
    subject = models.CharField(max_length=75)
    message = models.TextField(max_length=200)
    sender = models.EmailField()

class Customers(models.Model):
    fname = models.CharField(max_length=25)
    lname = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()

main/forms.py
from django import forms
from django.core.mail import send_mail

from .models import Contacts, Customers

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contacts
        exclude = []

    def send_email(self):
				"""
				basic send_mail usage
				"""
				Contacts(
				     subject=self.subject,
						 message=self.message,
						 sender=self.sender).save()
				Customers(email=self.sender).save()
				send_mail(
					self.subject,
					self.message,
					self.sender,
					['kieran.farrar@gmail.com'],
				)
				pass

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customers
        exclude = []

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import FormView


from .forms import ContactForm, CustomerForm
from .models import Contacts, Customers


def index(request):
    return render(request, "main/index.html")


def about(request):
    return render(request, "main/about.html")


def thanks(request):
    return render(request, "main/thanks.html")

class ContactsView(ListView):
    template_name = "main/contacts.html"
    context_object_name = "contacts"
    model = Contacts

    def get_queryset(self):
        """
        Return all Contacts that have been submitted
        """
        return Contacts.objects.all()


class ContactView(FormView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # Write code for after form validation
        form.subject = form.cleaned_data['subject']
        form.message = form.cleaned_data['message']
        form.sender = form.cleaned_data['sender']

        form.send_email()
        return super(ContactView, self).form_valid(form)

class CustomersView(ListView):
    template_name = "main/customers.html"
    context_object_name = "customers"
    model = Customers

    def get_queryset(self):
        """
        Return all Customers that have been submitted
        """
        return Customers.objects.all()


def viewCustomer(request, customer_id):
		customer = get_object_or_404(Customers, pk=customer_id)
		return render(request, 'main/customer.html', {
			      'customer': customer,
						'error_message': "woopsy",
		    })

def editCustomer(request, customer_id):
    customer = Customers.objects.get(pk=customer_id)
    if request.method == "POST":
        form = CustomerForm(request.POST, instance=customer)
        form.save()
    return HttpResponseRedirect(reverse('main:customers'))

def deleteCustomer(request, customer_id):
    customer = Customers.objects.get(pk=customer_id).delete()
    return HttpResponseRedirect(reverse('main:customers'))

main/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}
    <h2>About</h2>
    <p>This is our awesome site. We hope you enjoy yourself.</p>
{% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Sup, World!</title>
</head>
<body>
<header>
    {% include "main/navigation.html" %}
</header>
<h1>Sup, World!</h1>
{% block content %}
    
{% endblock content %}
</body>
</html>

main/templates/main/contact.html
{% extends "main/base.html" %}
{% block content %}

<h2>Contact</h2>
<form action="{% url 'main:contact' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
	<div><input type="submit" value="Submit" /></div>
</form>

{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block content %}
    <h2>Home</h2>
    <p>
        We have spent many years desigining a website that will blow you away.
        Things you might get a chance to enjoy:
        <ul>
            <li>Eternal youth!</li>
            <li>Adoration of your peers!</li>
            <li>Endless summers!</li>
        </ul>
    </p>
{% endblock content %}

main/templates/main/navigation.html
<nav>
    <ul>
        <li><a href='{% url "main:index" %}'>Home</a></li>
        <li><a href='{% url "main:about" %}'>About</a></li>
        <li><a href='{% url "main:contact" %}'>Contact</a></li>
        <li><a href='{% url "main:contacts" %}'>Contacts</a></li>
        <li><a href='{% url "main:customers" %}'>Customers</a></li>
    </ul>
</nav>